import 'dart:async';
import 'dart:convert';
import 'package:flutter_js/flutter_js.dart';
import '../utils/logger.dart';
import '../models/execution_result.dart';

/// Edge Sandbox Core: Local JavaScript execution engine based on QuickJS.
/// Responsible for isolated execution of JS code generated by LLMs
/// and bridging native capabilities.
class ClawJSRuntime {
  JavascriptRuntime? _runtime;

  /// Handles asynchronous JS execution. Since Agent-generated code may contain
  /// async network requests, we must wait for the JS code to explicitly
  /// call `Claw.finish()` to retrieve the final result.
  Completer<ExecutionResult>? _executionCompleter;

  /// Initializes the sandbox environment
  Future<void> initialize() async {
    // Spin up a fresh QuickJS instance
    _runtime = getJavascriptRuntime();

    // Initialize the global 'Claw' namespace
    _runtime!.evaluate('var Claw = {};');

    // Register core lifecycle callback: Claw.finish
    // When the LLM finishes running code and obtains the business result,
    // it MUST call this method to notify the Dart layer.
    _runtime!.onMessage('Claw_finish', (dynamic args) {
      if (_executionCompleter != null && !_executionCompleter!.isCompleted) {
        // Parse the returned result (args is typically data sent from JS)
        String finalOutput = '';
        if (args is List && args.isNotEmpty) {
          finalOutput = args.first.toString();
        } else {
          finalOutput = args.toString();
        }

        // Successfully captured the result; complete the Dart-layer await.
        _executionCompleter!.complete(ExecutionResult(
          isSuccess: true,
          stdout: finalOutput,
          stderr: '',
        ));
      }
    });

    // Inject the functional implementation of Claw.finish into the JS environment
    _runtime!.evaluate('''
      Claw.finish = function(result) {
        // Serialize complex objects into JSON strings to pass back to Dart
        var resultStr = typeof result === 'object' ? JSON.stringify(result) : String(result);
        sendMessage('Claw_finish', JSON.stringify([resultStr]));
      };
    ''');

    Log.i('🛡️ Claw Edge Sandbox (QuickJS) initialization complete.');
  }

  /// Used by BridgeRegistry: Registers Dart functions into the JS sandbox.
  /// [methodName]: The method name called in JS, e.g., 'httpGet' -> becomes `Claw.httpGet`.
  /// [handler]: The processing function in the Dart layer.
  void registerBridgeMethod(String methodName, dynamic Function(List<dynamic>) handler) {
    if (_runtime == null) throw Exception('Sandbox not initialized');

    final channelName = 'Claw_$methodName';

    // 1. Register the Dart-layer listener
    _runtime!.onMessage(channelName, (dynamic args) {
      try {
        // Parse the JSON string array passed from JS into a Dart List
        List<dynamic> parsedArgs = [];
        if (args is List && args.isNotEmpty) {
          // The JS side sends arguments as a JSON-stringified array within the first element of args
          parsedArgs = jsonDecode(args.first.toString());
        }
        // Invoke native processing logic
        final result = handler(parsedArgs);
        // Ensure result is returned to JS as a JSON string if it's not a primitive
        return result is String ? result : jsonEncode(result);
      } catch (e, stack) {
        Log.e('❌ Bridge call error [$methodName]: $e', stackTrace: stack);
        return jsonEncode({"error": e.toString()});
      }
    });

    Log.i('🔗 Registered bridge method: Claw.$methodName');

    // 2. Inject the corresponding wrapper function into the JS layer
    _runtime!.evaluate('''
      Claw.$methodName = function(...args) {
        // flutter_js's sendMessage requires a channelName and an array of string parameters
        // We stringify the entire args array to pass it as a single message
        var res = sendMessage('$channelName', JSON.stringify([JSON.stringify(args)]));
        try {
           return JSON.parse(res);
        } catch(e) {
           return res; // Return raw string if it is not valid JSON
        }
      };
    ''');
  }

  /// Executes JavaScript code generated by the LLM.
  /// Includes timeout control and exception handling to prevent malicious
  /// code or infinite loops from freezing the App.
  Future<ExecutionResult> evaluate(String jsCode, {Duration timeout = const Duration(seconds: 30)}) async {
    if (_runtime == null) {
      return ExecutionResult.error('Sandbox not initialized. Call initialize() first.');
    }

    _executionCompleter = Completer<ExecutionResult>();

    try {
      Log.i('▶️ Starting code execution in sandbox...');

      // 1. Synchronously parse and execute the code
      final JsEvalResult evalResult = _runtime!.evaluate(jsCode);

      // 2. Check for syntax errors or synchronous runtime errors
      if (evalResult.isError) {
        return ExecutionResult.error('JS Execution Error: ${evalResult.stringResult}');
      }

      // 3. Begin timeout countdown
      // Because the actual result might be returned asynchronously via Claw.finish()
      return await _executionCompleter!.future.timeout(timeout);

    } on TimeoutException {
      // In case of an infinite loop or excessive duration, terminate execution.
      // (In production, it is recommended to dispose and rebuild the runtime here).
      return ExecutionResult.error('Execution timed out (${timeout.inSeconds}s). Possible infinite loop or slow network request.');
    } catch (e) {
      return ExecutionResult.error('Critical Sandbox Exception: $e');
    } finally {
      // Reset state
      _executionCompleter = null;
    }
  }

  /// Releases JS engine memory at the C/C++ layer.
  /// Extremely Important! This must be called when the App exits or the
  /// environment resets; otherwise, it will lead to severe memory leaks.
  void dispose() {
    _runtime?.dispose();
    _runtime = null;
    Log.i('🧹 Claw Edge Sandbox memory released.');
  }
}